spring:
  application:
    name: demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/metro-comm?serverTimezome=UTC&CharacterEncoding=UTF-8
    username: root
    password: yangsql98
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # SQL 문을 콘솔에 출력
        show_sql: true
        # 형식을 가독성 있게 출력
        format_sql: true

